# Generated by Django 5.0.7 on 2024-07-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='podsumowanie',
            field=models.TextField(default='Django jest naprawde fajny'),
        ),
    ]
