# Generated by Django 5.0.7 on 2024-07-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie', '0002_produkt_podsumowanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.CharField(choices=[('new', 'Nowy'), ('in_progress', 'W toku'), ('resolved', 'Rozwiązany')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='podsumowanie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
