# Generated by Django 5.0.7 on 2024-07-18 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie', '0004_remove_produkt_podsumowanie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='uzytkownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='nazwa',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
