# Generated by Django 5.0.7 on 2024-07-20 10:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie', '0006_historicalprodukt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='uzytkownik',
        ),
        migrations.CreateModel(
            name='HistoricalZadanie',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=250)),
                ('opis', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Nowy'), ('in_progress', 'W toku'), ('resolved', 'Rozwiązany')], default='new', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('przypisany_uzytkownik', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical zadanie',
                'verbose_name_plural': 'historical zadanies',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Zadanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=250)),
                ('opis', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Nowy'), ('in_progress', 'W toku'), ('resolved', 'Rozwiązany')], default='new', max_length=20)),
                ('przypisany_uzytkownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalProdukt',
        ),
        migrations.DeleteModel(
            name='Produkt',
        ),
    ]
